version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: oco_db
      POSTGRES_USER: oco_user
      POSTGRES_PASSWORD: oco_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oco_user -d oco_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: